<?php

namespace GeopagosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * favoritoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class favoritoRepository extends EntityRepository
{
}
