<?php

namespace GeopagosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioPagosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioPagosRepository extends EntityRepository
{
}
