pago_index:
    path:     /
    defaults: { _controller: "GeopagosBundle:Pago:index" }
    methods:  GET

pago_show:
    path:     /{codigopago}/show
    defaults: { _controller: "GeopagosBundle:Pago:show" }
    methods:  GET

pago_new:
    path:     /new
    defaults: { _controller: "GeopagosBundle:Pago:new" }
    methods:  [GET, POST]

pago_edit:
    path:     /{codigopago}/edit
    defaults: { _controller: "GeopagosBundle:Pago:edit" }
    methods:  [GET, POST]

pago_delete:
    path:     /{codigopago}/delete
    defaults: { _controller: "GeopagosBundle:Pago:delete" }
    methods:  DELETE
